//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfiliadosCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AfiliadosCliente()
        {
            this.Conciliaciones = new HashSet<Conciliacione>();
        }
    
        public int AfiliadosClienteId { get; set; }
        public int ClienteId { get; set; }
        public int AfiliadoId { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conciliacione> Conciliaciones { get; set; }
    }
}
