//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsegurablesRole
    {
        public int AsegurablesRolId { get; set; }
        public int RolId { get; set; }
        public int AsegurableId { get; set; }
    
        public virtual Asegurable Asegurable { get; set; }
        public virtual Role Role { get; set; }
    }
}
