//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiariosClientesCompra
    {
        public int BeneficiariosClientesCompraId { get; set; }
        public int BeneficiariosClienteId { get; set; }
        public int CompraId { get; set; }
    
        public virtual BeneficiariosCliente BeneficiariosCliente { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
