//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.BeneficiariosClientesCompras = new HashSet<BeneficiariosClientesCompra>();
            this.DetallesCompras = new HashSet<DetallesCompra>();
        }
    
        public int CompraId { get; set; }
        public int AfiliadoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public string NumeroFactura { get; set; }
        public string Estado { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiariosClientesCompra> BeneficiariosClientesCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesCompra> DetallesCompras { get; set; }
    }
}
