//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conciliacione
    {
        public int ConciliacionId { get; set; }
        public int AfiliadosClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public string NroComprobante { get; set; }
    
        public virtual AfiliadosCliente AfiliadosCliente { get; set; }
    }
}
