//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalencia
    {
        public int EquivalenciaId { get; set; }
        public int Puntos { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
