//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoneyPoints_dlloEntities : DbContext
    {
        public MoneyPoints_dlloEntities()
            : base("name=MoneyPoints_dlloEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }

        
        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliado> Afiliados { get; set; }
        public virtual DbSet<AfiliadosCliente> AfiliadosClientes { get; set; }
        public virtual DbSet<Asegurable> Asegurables { get; set; }
        public virtual DbSet<AsegurablesRole> AsegurablesRoles { get; set; }
        public virtual DbSet<Beneficiario> Beneficiarios { get; set; }
        public virtual DbSet<BeneficiariosCliente> BeneficiariosClientes { get; set; }
        public virtual DbSet<BeneficiariosClientesCompra> BeneficiariosClientesCompras { get; set; }
        public virtual DbSet<BeneficiariosPunto> BeneficiariosPuntos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Conciliacione> Conciliaciones { get; set; }
        public virtual DbSet<DetallesCompra> DetallesCompras { get; set; }
        public virtual DbSet<Equivalencia> Equivalencias { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Tercero> Terceros { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
