//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.MoneyPoints.Model.Bussiness.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int RolId { get; set; }
        public Nullable<int> TerceroId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Tercero Tercero { get; set; }
    }
}
